name: Terraform AWS Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

env:
  AWS_REGION: us-east-2
  TERRAFORM_VERSION: 1.4.6
  SENDER_EMAIL: notifications@example.com

permissions:
  contents: read

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install boto3 pytest boto3-stubs[essential] mypy-boto3-ses mypy-boto3-dynamodb
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}
        terraform_wrapper: false
    
    - name: Terraform Format
      id: fmt
      run: terraform fmt -check -recursive
      continue-on-error: true
    
    - name: Terraform Init
      id: init
      run: terraform init
    
    - name: Terraform Validate
      id: validate
      run: terraform validate
    
    - name: Terraform Plan
      id: plan
      if: github.event_name == 'pull_request'
      run: |
        # Generate a timestamp-based suffix for resources
        TIMESTAMP=$(date +%Y%m%d%H%M%S)
        terraform plan -no-color -var="aws_region=${{ env.AWS_REGION }}" -var="resource_suffix=tf${TIMESTAMP}"
      continue-on-error: true
    
    - name: Update Pull Request
      uses: actions/github-script@v6
      if: github.event_name == 'pull_request'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
          #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
          #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
          #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
          
          <details><summary>Show Plan</summary>
          
          \`\`\`terraform
          ${{ steps.plan.outputs.stdout }}
          \`\`\`
          
          </details>`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })
    
    - name: Setup SES for Email Notifications
      if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
      id: setup_ses
      run: |
        # Check if email is already verified using a safer approach
        # The email address needs to be escaped in the JSON query
        EMAIL_ESCAPED=$(echo ${{ env.SENDER_EMAIL }} | sed 's/@/\\@/g')
        
        # First, list all verified identities
        VERIFIED_EMAILS=$(aws ses list-identities --identity-type EmailAddress --output json)
        
        # Check if our email is in the list
        if echo "$VERIFIED_EMAILS" | grep -q "${{ env.SENDER_EMAIL }}"; then
          echo "SES email already verified: ${{ env.SENDER_EMAIL }}"
        else
          echo "Verifying SES email identity: ${{ env.SENDER_EMAIL }}"
          aws ses verify-email-identity --email-address ${{ env.SENDER_EMAIL }}
          echo "Please check your email and verify the sender address before sending emails"
          echo "::warning::SES email verification required for ${{ env.SENDER_EMAIL }}"
        fi
      continue-on-error: true
    
    - name: Package Lambda Functions
      if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
      run: |
        # Use the improved packaging script
        chmod +x ziplambda.sh
        ./ziplambda.sh
    
    - name: Terraform Apply
      if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
      run: |
        # Generate a timestamp-based suffix for resources
        TIMESTAMP=$(date +%Y%m%d%H%M%S)
        terraform apply -auto-approve -var="aws_region=${{ env.AWS_REGION }}" -var="resource_suffix=tf${TIMESTAMP}"
    
    - name: Capture Terraform Outputs
      if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
      id: tf_outputs
      run: |
        echo "API_URL=$(terraform output -raw api_url)" >> $GITHUB_OUTPUT
        echo "USER_POOL_ID=$(terraform output -raw user_pool_id)" >> $GITHUB_OUTPUT
        echo "APP_CLIENT_ID=$(terraform output -raw cognito_app_client_id)" >> $GITHUB_OUTPUT
        echo "COGNITO_DOMAIN=$(terraform output -raw cognito_domain)" >> $GITHUB_OUTPUT
        echo "HOSTED_UI_URL=$(terraform output -raw hosted_ui_url)" >> $GITHUB_OUTPUT
    
    - name: Run Test Suite
      if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
      run: |
        if [ -d "tests" ]; then
          pytest -xvs tests/
        else
          echo "No tests directory found, skipping tests"
        fi
      continue-on-error: true
    
    - name: Deployment Summary
      if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
      run: |
        echo "## Deployment Complete ✅" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### API Endpoint" >> $GITHUB_STEP_SUMMARY
        echo "${{ steps.tf_outputs.outputs.API_URL }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Cognito User Pool" >> $GITHUB_STEP_SUMMARY
        echo "User Pool ID: ${{ steps.tf_outputs.outputs.USER_POOL_ID }}" >> $GITHUB_STEP_SUMMARY
        echo "App Client ID: ${{ steps.tf_outputs.outputs.APP_CLIENT_ID }}" >> $GITHUB_STEP_SUMMARY
        echo "Cognito Domain: ${{ steps.tf_outputs.outputs.COGNITO_DOMAIN }}" >> $GITHUB_STEP_SUMMARY
        echo "Hosted UI URL: ${{ steps.tf_outputs.outputs.HOSTED_UI_URL }}" >> $GITHUB_STEP_SUMMARY 